### ISSUE TITLE
启动期间乱按键盘导致快捷键失效

### ISSUE THREAD

**Issue by tignioj** [tignioj/minimap#6]
解决方案：启动的时候不要动键盘

日志信息
```
2024-09-26_20:34 - pynput.keyboard.Listener - ERROR - Unhandled exception in listener callback
Traceback (most recent call last):
  File "G:\software\anaconda\envs\gs_minimap\lib\site-packages\pynput\_util\__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "G:\software\anaconda\envs\gs_minimap\lib\site-packages\pynput\keyboard\_win32.py", line 316, in _process
    self.on_press(key)
  File "G:\software\anaconda\envs\gs_minimap\lib\site-packages\pynput\_util\__init__.py", line 145, in inner
    if f(*args) is False:
  File "G:\PyCharmProgram\minimap\minimap\server\MiniMapServer.py", line 37, in _on_press
    if socketio_instance: socketio_instance.emit(SOCKET_EVENT_KEYBOARD, {'key': c})
  File "G:\software\anaconda\envs\gs_minimap\lib\site-packages\flask_socketio\__init__.py", line 462, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
AttributeError: 'NoneType' object has no attribute 'emit'
```

**Comment by tignioj** [comment]
590e75759f48c0a5130a87350b79ece7fd304bb2
